AcousticAbsorptionCalc/core/urls.py
from core.views import HomeView
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("users/", include("users.urls", namespace="users")),
    path("user_logs/", include("user_logs.urls", namespace="user-logs")),
    path("projects/", include("projects.urls")),
    path("rooms/", include("rooms.urls")),
    path("calculations/", include("calculations.urls")),
    path("plans/", include("plans.urls", namespace="plans")),
    path("project_logs/", include("project_logs.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

AcousticAbsorptionCalc/plans/urls.py
from django.urls import path

from .views import (
    CreateCheckoutSessionView,
    PaymentCancelView,
    PaymentSuccessView,
    PlanListView,
    StripeWebhookView,
)

app_name = "plans"

urlpatterns = [
    path("", PlanListView.as_view(), name="plan_list"),
    path(
        "create-checkout-session/",
        CreateCheckoutSessionView.as_view(),
        name="create_checkout_session",
    ),
    path("webhook/", StripeWebhookView.as_view(), name="stripe_webhook"),
    path("payment/success/", PaymentSuccessView.as_view(), name="payment_success"),
    path("payment/cancel/", PaymentCancelView.as_view(), name="payment_cancel"),
]

AcousticAbsorptionCalc/projects/urls.py
from django.urls import path

from .views import (
    ProjectCreateView,
    ProjectCSVView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
    ProjectPDFView,
    ProjectRoomCreateView,
    ProjectRoomDeleteView,
    ProjectRoomUpdateView,
    ProjectUpdateView,
)

app_name = "projects"

urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("create/", ProjectCreateView.as_view(), name="project_create"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("<int:pk>/update/", ProjectUpdateView.as_view(), name="project_update"),
    path("<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete"),
    path(
        "<int:project_id>/download-pdf/",
        ProjectPDFView.as_view(),
        name="project_pdf",
    ),
    path(
        "projects/<int:project_id>/rooms/new/",
        ProjectRoomCreateView.as_view(),
        name="room_create",
    ),
    path(
        "projects/rooms/<int:pk>/edit/",
        ProjectRoomUpdateView.as_view(),
        name="room_edit",
    ),
    path(
        "projects/rooms/<int:pk>/delete/",
        ProjectRoomDeleteView.as_view(),
        name="room_delete",
    ),
    path(
        "<int:project_id>/download-csv/",
        ProjectCSVView.as_view(),
        name="project_csv",
    ),
]

AcousticAbsorptionCalc/rooms/urls.py
from django.urls import path

from .views import (
    RoomCalculationSummaryView,
    RoomCreateView,
    RoomDeleteView,
    RoomListView,
    RoomUpdateView,
)

app_name = "rooms"

urlpatterns = [
    path("", RoomListView.as_view(), name="room_list"),
    path("<int:pk>/delete/", RoomDeleteView.as_view(), name="room_delete"),
    path("create/", RoomCreateView.as_view(), name="room_create"),
    path("<int:pk>/edit/", RoomUpdateView.as_view(), name="room_edit"),
    path(
        "rooms/<int:pk>/summary/",
        RoomCalculationSummaryView.as_view(),
        name="room_summary",
    ),
]

AcousticAbsorptionCalc/users/urls.py
from django.urls import path

from .views import (
    HomeView,
    LoginView,
    LogoutView,
    PasswordResetRequestView,
    RegisterView,
    UserProfileUpdateView,
)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("profile/edit/", UserProfileUpdateView.as_view(), name="edit_profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("home", HomeView.as_view(), name="home"),
    path(
        "password-reset/",
        PasswordResetRequestView.as_view(),
        name="password_reset_request",
    ),
]

AcousticAbsorptionCalc/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>
            {% block title %}iLanding App{% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="{% static 'ilanding/assets/img/favicon.png' %}" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
              rel="stylesheet" />
        <link href="{% static 'ilanding/assets/vendor/bootstrap/css/bootstrap.min.css' %}"
              rel="stylesheet" />
        <link href="{% static 'ilanding/assets/css/main.css' %}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css"
              rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css"
              rel="stylesheet" />
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        {% block header %}
            <header id="header" class="sticky-top">
                <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
                    <div class="container">
                        <a class="navbar-brand" href="{% url 'users:home' %}">{% trans "Acoustic Absorption Calculator" %}</a>
                        <button class="navbar-toggler mobile-nav-toggle" type="button">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse navmenu" id="navbarNav">
                            <ul class="navbar-nav me-auto">
                                <li class="nav-item">
                                    <a class="nav-link {% if request.resolver_match.url_name == 'project_list' %}active{% endif %}"
                                       href="{% url 'projects:project_list' %}">{% trans "Projects" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% if request.resolver_match.url_name == 'plan_list' %}active{% endif %}"
                                       href="{% url 'plans:plan_list' %}">{% trans "Plans" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% if request.resolver_match.url_name == 'room_list' %}active{% endif %}"
                                       href="{% url 'rooms:room_list' %}">{% trans "Rooms" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% if request.resolver_match.url_name == 'user-logs' %}active{% endif %}"
                                       href="{% url 'user-logs:user-logs' %}">{% trans "Account History" %}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% if request.resolver_match.url_name == 'edit_profile' %}active{% endif %}"
                                       href="{% url 'users:edit_profile' %}">{% trans "Account Settings" %}</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-outline-danger">{% trans "Log Out" %}</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        {% endblock %}
        <main id="main">
            {% block content %}{% endblock %}
        </main>
        <div class="scroll-top"
             style="display: none;
                    position: fixed;
                    bottom: 20px;
                    right: 20px;
                    cursor: pointer">⬆️</div>
        {% block footer %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@srexi/purecounterjs/dist/purecounter_vanilla.js"></script>
        <script src="{% static 'ilanding/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'ilanding/assets/js/main.js' %}"></script>
        {% block extra_js %}{% endblock %}
    </body>
</html>

AcousticAbsorptionCalc/templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ app_title }}{% endblock %}
{% block header %}{% endblock %}
{#  #}
{% block content %}
    <div class="container text-center mt-5">
        <h1 class="mb-4">{{ app_title }}</h1>
        <p class="mb-4">{{ description }}</p>
        <div class="d-flex justify-content-center gap-3">
            <a href="{% url 'users:login' %}" class="btn btn-primary">{{ login_text }}</a>
            <a href="{% url 'users:register' %}" class="btn btn-success">{{ register_text }}</a>
        </div>
    </div>
{% endblock %}