AcousticAbsorptionCalc/core/urls.py
from core.views import HomeView
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("users/", include("users.urls", namespace="users")),
    path("user_logs/", include("user_logs.urls", namespace="user-logs")),
    path("projects/", include("projects.urls")),
    path("rooms/", include("rooms.urls")),
    path("calculations/", include("calculations.urls")),
    path("plans/", include("plans.urls", namespace="plans")),
    path("project_logs/", include("project_logs.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

AcousticAbsorptionCalc/projects/urls.py
from django.urls import path

from .views import (
    ProjectCreateView,
    ProjectCSVView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
    ProjectPDFView,
    ProjectRoomCreateView,
    ProjectRoomDeleteView,
    ProjectRoomUpdateView,
    ProjectUpdateView,
)

app_name = "projects"

urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("create/", ProjectCreateView.as_view(), name="project_create"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("<int:pk>/update/", ProjectUpdateView.as_view(), name="project_update"),
    path("<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete"),
    path(
        "<int:project_id>/download-pdf/",
        ProjectPDFView.as_view(),
        name="project_pdf",
    ),
    path(
        "projects/<int:project_id>/rooms/new/",
        ProjectRoomCreateView.as_view(),
        name="room_create",
    ),
    path(
        "projects/rooms/<int:pk>/edit/",
        ProjectRoomUpdateView.as_view(),
        name="room_edit",
    ),
    path(
        "projects/rooms/<int:pk>/delete/",
        ProjectRoomDeleteView.as_view(),
        name="room_delete",
    ),
    path(
        "<int:project_id>/download-csv/",
        ProjectCSVView.as_view(),
        name="project_csv",
    ),
]

AcousticAbsorptionCalc/rooms/urls.py
from django.urls import path

from .views import (
    RoomCalculationSummaryView,
    RoomCreateView,
    RoomDeleteView,
    RoomListView,
    RoomUpdateView,
)

app_name = "rooms"

urlpatterns = [
    path("", RoomListView.as_view(), name="room_list"),
    path("<int:pk>/delete/", RoomDeleteView.as_view(), name="room_delete"),
    path("create/", RoomCreateView.as_view(), name="room_create"),
    path("<int:pk>/edit/", RoomUpdateView.as_view(), name="room_edit"),
    path(
        "rooms/<int:pk>/summary/",
        RoomCalculationSummaryView.as_view(),
        name="room_summary",
    ),
]

AcousticAbsorptionCalc/projects/models.py
from django.db import models
from users.models import User


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    active_version = models.ForeignKey(
        "ProjectVersion",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "name")


class SharedProject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    shared_with_user = models.ForeignKey(User, on_delete=models.CASCADE)
    access_level = models.CharField(max_length=50)


class ProjectNote(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    room = models.ForeignKey("rooms.Room", on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class ProjectVersion(models.Model):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="versions"
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("project", "name")

    def __str__(self):
        return f"{self.project.name} - {self.name}"

    def set_active(self):
        ProjectVersion.objects.filter(project=self.project).update(is_active=False)

        self.is_active = True
        self.save()

        self.project.active_version = self
        self.project.save(update_fields=["active_version"])


class ProjectVersionChange(models.Model):
    class EntityType(models.IntegerChoices):
        ROOM = 1, "Room"
        MATERIAL = 2, "Material"
        FURNISHING = 3, "Furnishing"
        OTHER = 4, "Other"

    class ChangeType(models.IntegerChoices):
        CREATE = 1, "Created"
        UPDATE = 2, "Updated"
        DELETE = 3, "Deleted"

    project_version = models.ForeignKey(
        "projects.ProjectVersion", on_delete=models.CASCADE, related_name="changes"
    )
    entity_type = models.IntegerField(choices=EntityType.choices)
    entity_id = models.IntegerField(null=True, blank=True)
    change_type = models.IntegerField(choices=ChangeType.choices)
    changed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    data = models.JSONField(blank=True, null=True)

    def __str__(self):
        return f"{self.get_change_type_display()} {self.get_entity_type_display()} (ID: {self.entity_id})"

AcousticAbsorptionCalc/projects/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description"]

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()
        return instance

AcousticAbsorptionCalc/projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q, QuerySet
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    View,
)
from plans.models import UserPlan
from project_logs.projectlogger import ProjectLogger
from projects.forms import ProjectForm
from projects.services import CSVExportService, PDFGeneratorService
from pyexpat.errors import messages
from rooms.forms import FurnishingFormSet, RoomForm
from rooms.models import Room
from user_logs.logger import Logger

from .models import Project
from .permissions import can_edit_project, can_view_project
from .project_services import ProjectService


class ProjectCreateView(LoginRequiredMixin, CreateView):
    template_name = "projects/project_create.html"
    form_class = ProjectForm
    success_url = reverse_lazy("projects:project_list")

    def form_valid(self, form):
        user = self.request.user

        user_plan = (
            UserPlan.objects.select_related("plan")
            .filter(user=user, is_active=True)
            .first()
        )

        if user_plan:
            max_projects = user_plan.plan.max_projects
            current_project_count = Project.objects.filter(user=user).count()

            if current_project_count >= max_projects:
                messages.error(
                    self.request, _("Project limit reached for your current plan.")
                )
                return self.form_invalid(form)

        name = form.cleaned_data["name"]
        description = form.cleaned_data["description"]

        project = ProjectService.create_project(
            user=user, name=name, description=description
        )

        Logger.log_project_created(user_id=project.pk, changed_by=user)
        ProjectLogger.log_created(
            project=project,
            changed_by=user,
            change_description="Project created via form",
        )

        return redirect(self.get_success_url())


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/project_form.html"
    success_url = reverse_lazy("projects:project_list")

    def test_func(self):
        project = self.get_object()
        return can_edit_project(self.request.user, project)

    def form_valid(self, form):
        old_instance = self.get_object()
        response = super().form_valid(form)

        Logger.log_project_updated(user_id=self.object.pk, changed_by=self.request.user)

        metadata = {}
        for field in form.changed_data:
            metadata[field] = {
                "old": getattr(old_instance, field),
                "new": form.cleaned_data.get(field),
            }

        ProjectLogger.log_edit_dimensions(
            project=self.object,
            changed_by=self.request.user,
            change_description="Project fields updated",
            metadata=metadata,
        )

        return response


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    template_name = "projects/project_confirm_delete.html"
    success_url = reverse_lazy("projects:project_list")

    def test_func(self):
        project = self.get_object()
        return can_edit_project(self.request.user, project)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()

        Logger.log_project_deleted(user_id=self.object.pk, changed_by=request.user)

        ProjectLogger.log_deleted(
            project=self.object,
            changed_by=request.user,
            change_description="Project deleted by user",
        )

        return super().delete(request, *args, **kwargs)


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/projects_list.html"
    context_object_name = "projects"

    def get_queryset(self) -> QuerySet[Project]:
        queryset = super().get_queryset()
        user = self.request.user
        if user.is_staff:
            return queryset

        return queryset.filter(
            Q(user=user) | Q(sharedproject__shared_with_user=user)
        ).distinct()


class ProjectDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Project
    template_name = "projects/project_detail.html"
    context_object_name = "project"

    def test_func(self):
        project = self.get_object()
        return can_view_project(self.request.user, project)


class ProjectPDFView(View):
    def get(self, request, project_id):
        try:
            project = Project.objects.prefetch_related("rooms").get(id=project_id)
        except Project.DoesNotExist:
            raise Http404("Project does not exist")

        Logger.log_project_updated(user_id=project.pk, changed_by=request.user)

        ProjectLogger.log_downloaded(
            project=project,
            changed_by=request.user,
            change_description="Project PDF downloaded",
        )

        context = {
            "project": project,
            "rooms": project.rooms.all(),
        }

        pdf_content = PDFGeneratorService.generate_project_pdf(context)

        response = HttpResponse(pdf_content, content_type="application/pdf")
        response["Content-Disposition"] = f'inline; filename="project_{project.id}.pdf"'
        return response


class ProjectRoomCreateView(CreateView):
    model = Room
    form_class = RoomForm
    template_name = "rooms/room_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["furnishing_formset"] = FurnishingFormSet(self.request.POST)
        else:
            context["furnishing_formset"] = FurnishingFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["furnishing_formset"]

        if formset.is_valid():
            form.instance.project_id = self.kwargs.get("project_id")
            response = super().form_valid(form)

            furnishings = {
                f.cleaned_data["material"].name: f.cleaned_data["area"]
                for f in formset
                if f.cleaned_data and not f.cleaned_data.get("DELETE", False)
            }

            Logger.log_room_created(
                user_id=self.object.pk, changed_by=self.request.user
            )

            ProjectLogger.log_created(
                project=self.object.project,
                changed_by=self.request.user,
                change_description=f"Room '{form.cleaned_data['name']}' created",
                metadata=furnishings,
            )

            return response
        return self.form_invalid(form)

    def get_success_url(self):
        return reverse_lazy(
            "rooms:room_list", kwargs={"project_id": self.kwargs.get("project_id")}
        )


class ProjectRoomUpdateView(UpdateView):
    model = Room
    form_class = RoomForm
    template_name = "rooms/project_room_form.html"
    context_object_name = "room"

    def form_valid(self, form):
        old_name = self.object.name
        old_area = self.object.area

        response = super().form_valid(form)

        Logger.log_room_updated(user_id=self.object.pk, changed_by=self.request.user)

        ProjectLogger.log_edit_furnishing(
            project=self.object.project,
            changed_by=self.request.user,
            change_description=f"Room '{old_name}' updated in project.",
            metadata={
                "room_id": self.object.pk,
                "old_name": old_name,
                "new_name": self.object.name,
                "old_area": old_area,
                "new_area": self.object.area,
            },
        )

        return response

    def get_success_url(self):
        return reverse_lazy(
            "rooms:room_list", kwargs={"project_id": self.object.project_id}
        )


class ProjectRoomDeleteView(DeleteView):
    model = Room
    template_name = "rooms/room_confirm_delete.html"
    context_object_name = "room"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        project = self.object.project
        room_name = self.object.name
        room_id = self.object.pk

        Logger.log_room_deleted(user_id=room_id, changed_by=request.user)

        ProjectLogger.log_deleted(
            project=project,
            changed_by=request.user,
            change_description=f"Room '{room_name}' deleted",
            metadata={"room_id": room_id},
        )

        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy(
            "rooms:room_list", kwargs={"project_id": self.object.project_id}
        )


class ProjectCSVView(View):
    def get(self, request, project_id):
        try:
            project = Project.objects.prefetch_related("rooms").get(id=project_id)
        except Project.DoesNotExist:
            raise Http404(_("Project does not exist"))

        return CSVExportService.generate_project_csv(project)

AcousticAbsorptionCalc/templates/projects/project_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="container mt-5">
        <div class="card shadow-sm">
            <div class="card-body">
                <h3 class="card-title text-danger">
                    {% blocktrans with project_name=object.name %}
          Are you sure you want to delete the project "{{ project_name }}"?
        {% endblocktrans %}
                </h3>
                <p class="text-muted">{% trans "This action cannot be undone." %}</p>
                <form method="post" class="mt-4 d-flex gap-3">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                    <a href="{% url 'projects:project_detail' object.pk %}"
                       class="btn btn-secondary">{% trans "Cancel" %}</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

AcousticAbsorptionCalc/templates/projects/project_create.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container">
        <h1>{% trans "Create a New Project" %}</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="{{ form.name.id_for_label }}" class="form-label">{% trans "Project Name" %}</label>
                {{ form.name|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="{{ form.description.id_for_label }}" class="form-label">{% trans "Project Description" %}</label>
                {{ form.description|add_class:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">{% trans "Create Project" %}</button>
        </form>
        <div class="mt-4">
            <a href="{% url 'projects:project_list' %}" class="btn btn-secondary">{% trans "Back to Project List" %}</a>
        </div>
    </div>
{% endblock %}

AcousticAbsorptionCalc/templates/projects/project_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="container mt-5">
        <div class="card shadow-sm">
            <div class="card-body">
                <h2 class="card-title">{{ project.name }}</h2>
                <p class="card-text">{{ project.description }}</p>
                <div class="d-flex gap-3 mb-4">
                    <a href="{% url 'projects:project_update' project.pk %}"
                       class="btn btn-warning">{% trans "Edit Project" %}</a>
                    <a href="{% url 'projects:project_delete' project.pk %}"
                       class="btn btn-danger">{% trans "Delete Project" %}</a>
                </div>
                <!-- Section for PDF and CSV downloads -->
                <div class="d-flex gap-3 mb-4">
                    <a href="{% url 'projects:project_pdf' project.pk %}"
                       class="btn btn-primary">{% trans "Generate PDF" %}</a>
                    <a href="{% url 'projects:project_csv' project.pk %}"
                       class="btn btn-secondary">{% trans "Download CSV" %}</a>
                </div>
                <hr>
                <h3 class="mt-4">{% trans "Rooms" %}</h3>
                <ul class="list-group">
                    {% for room in project.rooms.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'projects:room_detail' room.pk %}">{{ room.name }}</a>
                            <div>
                                <a href="{% url 'projects:room_edit' room.pk %}"
                                   class="btn btn-sm btn-warning">{% trans "Edit" %}</a>
                                <a href="{% url 'projects:room_confirm_delete' room.pk %}"
                                   class="btn btn-sm btn-danger">{% trans "Delete" %}</a>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">{% trans "No rooms available" %}</li>
                    {% endfor %}
                </ul>
                <div class="mt-4">
                    <a href="{% url 'rooms:room_create' project.pk %}"
                       class="btn btn-success">{% trans "Add Room" %}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

AcousticAbsorptionCalc/templates/projects/project_detail_pdf.html
{% extends "basic.html" %}
{% load i18n %}
{% block content %}
    <section class="section mt-5">
        <div class="container">
            <div class="mb-4">
                <h1 class="mb-3">{% trans "Project:" %} {{ project.name }}</h1>
                <p>
                    <strong>{% trans "Description:" %}</strong> {{ project.description }}
                </p>
                <p>
                    <strong>{% trans "Creation date:" %}</strong> {{ project.created_at|date:"d.m.Y" }}
                </p>
            </div>
            <h2 class="mb-3">{% trans "Rooms" %}</h2>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="table-light">
                        <tr>
                            <th scope="col">{% trans "Name" %}</th>
                            <th scope="col">{% trans "Area (m²)" %}</th>
                            <th scope="col">{% trans "Description" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for room in rooms %}
                            <tr>
                                <td>{{ room.name }}</td>
                                <td>{{ room.area }}</td>
                                <td>{{ room.description }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3" class="text-center">{% trans "No rooms in this project." %}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
{% endblock %}

AcousticAbsorptionCalc/templates/projects/projects_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="container">
        <h1>{% trans "Your Projects" %}</h1>
        <div class="mb-4">
            <a href="{% url 'projects:project_create' %}" class="btn btn-primary">{% trans "Create New Project" %}</a>
        </div>
        {% if projects %}
            <ul class="list-group">
                {% for project in projects %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div>
                            <h5>{{ project.name }}</h5>
                            <p class="mb-0">{{ project.description }}</p>
                        </div>
                        <div>
                            <a href="{% url 'projects:project_detail' project.pk %}"
                               class="btn btn-info btn-sm me-2">{% trans "Details" %}</a>
                            <a href="{% url 'projects:project_delete' project.pk %}"
                               class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>{% trans "You haven't created any projects yet." %}</p>
        {% endif %}
    </div>
{% endblock %}